export default [{
    id: '5',
    "image": "https://st-troy.mncdn.com/mnresize/1500/1500/Content/media/ProductImg/original/mlln3tua-apple-iphone-13-pro-max-1tb-sierra-mavisi-637678442923020072.jpg",
    "images":["https://st-troy.mncdn.com/mnresize/1500/1500/Content/media/ProductImg/original/mll63tua-apple-iphone-13-pro-max-128gb-grafit-637678409358576715.jpg", "https://www.apple.com/v/iphone-13-pro/f/images/meta/iphone-13-pro_overview__f8jyv9tx1pe2_og.png", "https://www.apple.com/v/iphone-13-pro/f/images/overview/display/gaming_endframe__jr57fnqnmde2_large.jpg"],
    "brand": "Apple",
    "price": 32.999,
    "rating": 1,
    "numReviews": 0,
    "isFeatured": true,
    "name": "iPhone 13 Pro Max 256GB",
    "description": "Apple iPhone 13 Pro Max 256GB 6.7 inç ekran gelişmiş çift kamera",
    "category": 1,
    "countInStock": 25,
    "type": "share"
  },{
    id: '6',
    "image": "https://cdn.dsmcdn.com/mnresize/500/-/ty32/product/media/images/20210326/23/75554837/108939192/1/1_org.jpg",
    "images":["https://cdn.akakce.com/sony/ps5-825-gb-ssd-z.jpg", "https://bugun24.com/uploads/2022/03/sony-ps5-pro-geliyor-gizemli-konsol-ilk-kez-gorundu-IcA5kvfI.jpg", "https://teknomers.com/wp-content/uploads/2022/04/Sony-PS5-icin-degisken-yenileme-hizi-destegini-onayladi-bilmeniz.jpg"],
    "brand": "SONY",
    "price": 14.999,
    "rating": 5,
    "numReviews": 0,
    "isFeatured": true,
    "name": "PS5 Standart Edition SSD Oyun Konsolu",
    "description": "Sony PS5 Standart Edition SSD Oyun Konsolu 1TB 2 Kol Hediyeli",
    "category": 2,
    "countInStock": 10,
    "type": "info"
  },{
    id: '7',
    "image": "https://s.turkcell.com.tr/SiteAssets/Cihaz/aksesuar/Apple/airpods-3-nesil/cg/1.png",
    "images":["https://cdn.akakce.com/apple/airpods-3-nesil-z.jpg", "https://cdn03.ciceksepeti.com/cicek/kcm43937422-1/XL/premium-airpods-pro-3.nesil-kablosuz-sarj-bluetooth-kulaklik-anc-kcm43937422-1-ed6a4f3811e94de095879923210982fd.jpg", "https://cdn.cimri.io/image/1000x1000/trktechairpodspronesilbluetoothkulaklk_526720625.jpg"],
  
    "brand": "Apple",
    "price": 5499.9,
    "rating": 5,
    "numReviews": 0,
    "isFeatured": true,
    "name": "Apple AirPods 3. Nesil Kulaklık",
    "description": "Apple AirPods 3. Nesil Bluetooth Kulaklık",
    "category": 3,
    "countInStock": 10,
    "type": "share"
  },{
    id: '8',
    "image": "https://cdn.akakce.com/beats/beats-studio3-wireless-anc-aktif-gurultu-onleyici-kablosuz-kulak-ustu-kulaklik-z.jpg",
    "images":["https://i0.shbdn.com/photos/09/41/34/x5_1006094134n0s.jpg", "https://i.dr.com.tr/cache/500x400-0/originals/0001921397001-3.jpg", "https://www.beatsbydre.com/content/dam/beats/web/product/headphones/studio3-wireless/pdp/202010/studio3-pdp-p03-matte_black.jpg.large.1x.jpg"],
  
    "brand": "Beats",
    "price": 6799.9,
    "rating": 5,
    "numReviews": 0,
    "isFeatured": true,
    "name": "Beats Studio 3 Wireless Kulak Üstü Kulaklık",
    "description": "Beats Studio 3 Wireless Kulak Üstü Kulaklık Siyah",
    "category": 4,
    "countInStock": 5,
    "type": "info"
  },{
    id: '9',
    "image": "https://www.apple.com/newsroom/images/product/mac/standard/Apple_MacBook-Pro_16-inch-Screen_10182021_big_carousel.jpg.slideshow-xlarge_2x.jpg",
    "images":["https://www.apple.com/v/macbook-pro-14-and-16/b/images/meta/macbook-pro-14-and-16_overview__fz0lron5xyuu_og.png", "https://girisim.io/wp-content/uploads/2021/10/M1X-MBP-Feature.jpg", "https://www.apple.com/newsroom/images/product/mac/standard/Apple_MacBook-Pro_Ports_10182021_big_carousel.jpg.slideshow-medium_2x.jpg"],
    "brand": "Apple",
    "price": 51.999,
    "rating": 5,
    "numReviews": 0,
    "isFeatured": true,
    "name": "Apple MacBook Pro 2021 16 inç",
    "description": "Apple Macbook Pro 2021 16 inç 10 çekirdekli CPU 16 çekirdekli GPU 16 GB Birleşik Bellek 512 GB SSD Depolama",
    "category": 2,
    "countInStock": 2,
    "type": "share"
  },{
    id: '10',
    "image": "https://smartcdkeys.com/image/data/products/fifa-22/cover/fifa-22-ps5-smartcdkeys-cheap-cd-key-cover.jpg",
    "images":["https://i.ytimg.com/vi/vck7pnCjA-8/maxresdefault.jpg", "https://www.donanimhaber.com/images/images/haber/139719/src/fifa-22-ps5-ps4-xbox-series-one-pc-ve-stadia-icin-cikti139719_2.jpg", "https://updatecrazy.com/wp-content/uploads/2022/06/FIFA-22-Update-1.26-Patch-Notes-Official-1.jpg"],
    "brand": "FIFA",
    "price": 599,
    "rating": 5,
    "numReviews": 0,
    "isFeatured": true,
    "name": "Fifa 2022 PS5 Oyunu",
    "description": "Fifa 2022 PlayStation 5 Konsol Oyunu Orijinal",
    "category": 3,
    "countInStock": 2,
    "type": "info"
  }]